server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由ID，无固定规则，但建议配合服务名配置
#          uri: http://localhost:8001 #匹配后，提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后，提供服务的路由地址
          predicates:
            - Path=/payment/** #断言，路径相匹配进行路由
        - id: payment_routh2 # payment_route
#          uri:  http://localhost:8001
          uri: lb://cloud-payment-service #匹配后，提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
            - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
            #- Cookie=username   #带Cookie，并且username的值为zhansan
            #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式

eureka:
  client:
    register-with-eureka: true # false表示不向注册中心注册自己
    fetch-registry: true # false表示自己就是注册中心，负责维护服务实例，不需要检索服务
    service-url:
      # 设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个服务
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/